### ISSUE TITLE
Works in wildfly-30, not in eap-7.4

### ISSUE THREAD

**Issue by ericjvandervelden** [fjuma/wildfly-widgets#2]
In wildfly-30 it works, but in eap-7.4 no login screen appears. On localhost:8080/wildfly-widgets/inventory it says: Not found

**Comment by fjuma** [comment]
Hi @ericjvandervelden, we recently migrated this example to Jakarta EE to work with the latest version of WildFly (see https://github.com/fjuma/wildfly-widgets/pull/1).

Checking out and building from this older commit (https://github.com/fjuma/wildfly-widgets/commit/4b6fd1bd97ab4e95b07acbff2d7c08930b771e5d) should get things running on EAP.

**Comment by ericjvandervelden** [comment]
Thanks, it works.
